name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build APK
        run: eas build --platform android --profile release
        env:
          EAS_BUILD_PROFILE: release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: ./build/android/app/release/app-release.apk